apiVersion: v1
kind: Secret
metadata:
  name: px-vsphere-secret
  namespace: kube-system
type: Opaque
data:
  VSPHERE_USER: a2dvbnphbGV6Y2FyZG9uYUBwcmxiLmZsci5jMzYwY2xvdWQuY29t 
  VSPHERE_PASSWORD: OEw0Y0tkdTV0IQ== 